class AuditFields:
    CREATED_BY = "created_by"
    UPDATED_BY = "updated_by"


class WarehouseFields:
    ID = "id"
    CODE = "code"
    NAME = "name"
    ADDRESS = "address"
    MANAGER_NAME = "manager_name"
    IS_ACTIVE = "is_active"
    CREATED_BY = "created_by"
    UPDATED_BY = "updated_by"
    CREATED_AT = "created_at"
    UPDATED_AT = "updated_at"


class CategoryFields:
    ID = "id"
    NAME = "name"
    SLUG = "slug"
    PARENT = "parent"
    DESCRIPTION = "description"
    IS_ACTIVE = "is_active"
    CREATED_BY = "created_by"
    UPDATED_BY = "updated_by"
    CREATED_AT = "created_at"
    UPDATED_AT = "updated_at"


class SupplierFields:
    ID = "id"
    CODE = "code"
    NAME = "name"
    CONTACT_NAME = "contact_name"
    PHONE = "phone"
    EMAIL = "email"
    ADDRESS = "address"
    IS_ACTIVE = "is_active"
    CREATED_BY = "created_by"
    UPDATED_BY = "updated_by"
    CREATED_AT = "created_at"
    UPDATED_AT = "updated_at"


class ProductFields:
    ID = "id"
    SKU = "sku"
    NAME = "name"
    BARCODE = "barcode"
    CATEGORY = "category"
    CATEGORY_NAME = "category_name"
    SUPPLIER = "supplier"
    SUPPLIER_NAME = "supplier_name"
    SUPPLIER_CODE = "supplier_code"
    SUPPLIER_PHONE = "supplier_phone"
    SUPPLIER_ADDRESS = "supplier_address"
    SUPPLIER_STATUS = "supplier_status"
    BRAND = "brand"
    DESCRIPTION = "description"
    UNIT = "unit"
    COST_PRICE = "cost_price"
    SELLING_PRICE = "selling_price"
    TRACK_BATCH = "track_batch"
    TRACK_SERIAL = "track_serial"
    SHELF_LIFE_DAYS = "shelf_life_days"
    IS_ACTIVE = "is_active"
    QR_PAYLOAD = "qr_payload"
    QR_LABEL = "qr_label"
    CREATED_BY = "created_by"
    UPDATED_BY = "updated_by"
    CREATED_AT = "created_at"
    UPDATED_AT = "updated_at"


class InventoryFields:
    ID = "id"
    WAREHOUSE = "warehouse"
    WAREHOUSE_CODE = "warehouse_code"
    WAREHOUSE_NAME = "warehouse_name"
    PRODUCT = "product"
    PRODUCT_SKU = "product_sku"
    PRODUCT_NAME = "product_name"
    PRODUCT_UNIT = "product_unit"
    QUANTITY = "quantity"
    RESERVED_QUANTITY = "reserved_quantity"
    DAMAGED_QUANTITY = "damaged_quantity"
    AVAILABLE_QUANTITY = "available_quantity"
    REORDER_LEVEL = "reorder_level"
    SAFETY_STOCK = "safety_stock"
    MAX_STOCK_LEVEL = "max_stock_level"
    BIN_LOCATION = "bin_location"
    LAST_COUNTED_AT = "last_counted_at"
    IS_BELOW_REORDER_LEVEL = "is_below_reorder_level"
    QR_PAYLOAD = "qr_payload"
    QR_LABEL = "qr_label"
    CREATED_BY = "created_by"
    UPDATED_BY = "updated_by"
    CREATED_AT = "created_at"
    UPDATED_AT = "updated_at"


class ProductBatchFields:
    ID = "id"
    PRODUCT = "product"
    PRODUCT_SKU = "product_sku"
    WAREHOUSE = "warehouse"
    WAREHOUSE_CODE = "warehouse_code"
    BATCH_NO = "batch_no"
    MANUFACTURING_DATE = "manufacturing_date"
    EXPIRY_DATE = "expiry_date"
    QUANTITY = "quantity"
    RESERVED_QUANTITY = "reserved_quantity"
    SUPPLIER = "supplier"
    SUPPLIER_NAME = "supplier_name"
    CREATED_BY = "created_by"
    UPDATED_BY = "updated_by"
    CREATED_AT = "created_at"
    UPDATED_AT = "updated_at"


class SerialNumberFields:
    ID = "id"
    PRODUCT = "product"
    PRODUCT_SKU = "product_sku"
    WAREHOUSE = "warehouse"
    WAREHOUSE_CODE = "warehouse_code"
    BATCH = "batch"
    BATCH_NO = "batch_no"
    SERIAL_NUMBER = "serial_number"
    STATUS = "status"
    NOTE = "note"
    CREATED_BY = "created_by"
    UPDATED_BY = "updated_by"
    CREATED_AT = "created_at"
    UPDATED_AT = "updated_at"


class GoodsReceiptFields:
    ID = "id"
    RECEIPT_NO = "receipt_no"
    WAREHOUSE = "warehouse"
    WAREHOUSE_CODE = "warehouse_code"
    SUPPLIER = "supplier"
    SUPPLIER_NAME = "supplier_name"
    REFERENCE_NO = "reference_no"
    RECEIVED_AT = "received_at"
    STATUS = "status"
    NOTE = "note"
    APPROVED_BY = "approved_by"
    CREATED_BY = "created_by"
    UPDATED_BY = "updated_by"
    CREATED_AT = "created_at"
    UPDATED_AT = "updated_at"


class GoodsReceiptItemFields:
    ID = "id"
    GOODS_RECEIPT = "goods_receipt"
    RECEIPT_NO = "receipt_no"
    PRODUCT = "product"
    PRODUCT_SKU = "product_sku"
    BATCH = "batch"
    BATCH_NO = "batch_no"
    QUANTITY = "quantity"
    UNIT_COST = "unit_cost"
    NOTE = "note"
    CREATED_BY = "created_by"
    UPDATED_BY = "updated_by"
    CREATED_AT = "created_at"
    UPDATED_AT = "updated_at"


class GoodsIssueFields:
    ID = "id"
    ISSUE_NO = "issue_no"
    WAREHOUSE = "warehouse"
    WAREHOUSE_CODE = "warehouse_code"
    CUSTOMER_NAME = "customer_name"
    REFERENCE_NO = "reference_no"
    ISSUED_AT = "issued_at"
    STATUS = "status"
    NOTE = "note"
    APPROVED_BY = "approved_by"
    CREATED_BY = "created_by"
    UPDATED_BY = "updated_by"
    CREATED_AT = "created_at"
    UPDATED_AT = "updated_at"


class GoodsIssueItemFields:
    ID = "id"
    GOODS_ISSUE = "goods_issue"
    ISSUE_NO = "issue_no"
    PRODUCT = "product"
    PRODUCT_SKU = "product_sku"
    BATCH = "batch"
    BATCH_NO = "batch_no"
    QUANTITY = "quantity"
    UNIT_PRICE = "unit_price"
    NOTE = "note"
    CREATED_BY = "created_by"
    UPDATED_BY = "updated_by"
    CREATED_AT = "created_at"
    UPDATED_AT = "updated_at"


class StockMovementFields:
    ID = "id"
    WAREHOUSE = "warehouse"
    WAREHOUSE_CODE = "warehouse_code"
    PRODUCT = "product"
    PRODUCT_SKU = "product_sku"
    PRODUCT_NAME = "product_name"
    BATCH = "batch"
    BATCH_NO = "batch_no"
    SERIAL_NUMBER = "serial_number"
    GOODS_RECEIPT = "goods_receipt"
    GOODS_ISSUE = "goods_issue"
    STOCK_TRANSFER = "stock_transfer"
    STOCK_COUNT = "stock_count"
    MOVEMENT_TYPE = "movement_type"
    QUANTITY = "quantity"
    MOVEMENT_AT = "movement_at"
    REFERENCE_NO = "reference_no"
    REASON_CODE = "reason_code"
    QUANTITY_BEFORE = "quantity_before"
    QUANTITY_AFTER = "quantity_after"
    NOTE = "note"
    CREATED_BY = "created_by"
    UPDATED_BY = "updated_by"
    CREATED_AT = "created_at"
    UPDATED_AT = "updated_at"


class StockTransferFields:
    ID = "id"
    TRANSFER_NO = "transfer_no"
    SOURCE_WAREHOUSE = "source_warehouse"
    SOURCE_WAREHOUSE_CODE = "source_warehouse_code"
    DESTINATION_WAREHOUSE = "destination_warehouse"
    DESTINATION_WAREHOUSE_CODE = "destination_warehouse_code"
    STATUS = "status"
    TRANSFERRED_AT = "transferred_at"
    RECEIVED_AT = "received_at"
    NOTE = "note"
    APPROVED_BY = "approved_by"
    RECEIVED_BY = "received_by"
    CREATED_BY = "created_by"
    UPDATED_BY = "updated_by"
    CREATED_AT = "created_at"
    UPDATED_AT = "updated_at"


class StockTransferItemFields:
    ID = "id"
    TRANSFER = "transfer"
    TRANSFER_NO = "transfer_no"
    PRODUCT = "product"
    PRODUCT_SKU = "product_sku"
    BATCH = "batch"
    BATCH_NO = "batch_no"
    QUANTITY = "quantity"
    CREATED_BY = "created_by"
    UPDATED_BY = "updated_by"
    CREATED_AT = "created_at"
    UPDATED_AT = "updated_at"


class StockCountFields:
    ID = "id"
    COUNT_NO = "count_no"
    WAREHOUSE = "warehouse"
    WAREHOUSE_CODE = "warehouse_code"
    COUNTED_AT = "counted_at"
    STATUS = "status"
    NOTE = "note"
    COUNTED_BY = "counted_by"
    APPROVED_BY = "approved_by"
    CREATED_BY = "created_by"
    UPDATED_BY = "updated_by"
    CREATED_AT = "created_at"
    UPDATED_AT = "updated_at"


class StockCountItemFields:
    ID = "id"
    STOCK_COUNT = "stock_count"
    COUNT_NO = "count_no"
    PRODUCT = "product"
    PRODUCT_SKU = "product_sku"
    BATCH = "batch"
    BATCH_NO = "batch_no"
    EXPECTED_QUANTITY = "expected_quantity"
    COUNTED_QUANTITY = "counted_quantity"
    DIFFERENCE_QUANTITY = "difference_quantity"
    NOTE = "note"
    CREATED_BY = "created_by"
    UPDATED_BY = "updated_by"
    CREATED_AT = "created_at"
    UPDATED_AT = "updated_at"